fullscreen_hotkey: ctrl+f11
selecting_area_hotkey: ctrl+f12
foreground_screen_hotkey: ctrl+f10
directory_path: desktop

# Examples for directory_path values:
# directory_path: desktop
# directory_path: C:\Users\riobener\screenshot-taker
